# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: python:3.8

env:
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"
  # Increment the build number to force new mambaforge cache upload.
  MAMBA_CACHE_BUILD: "0"
  # Increment the build number to force new mint cache upload.
  MINT_CACHE_BUILD: "0"
  # Base environment conda packages to be installed
  MAMBA_CACHE_PACKAGES: "pip conda-lock"


docker_builder:
  name: builder py37
  alias: py37
  dummy_script:
    - echo "builder py37"

docker_builder:
  name: builder py36
  alias: py36
  dummy_script:
    - echo "builder py36"

dummy_task:
  matrix:
    - depends_on: py36
      env:
        PY: 36
    - depends_on: py37
      env:
        PY: 37
  name: dummy-task
  main_script:
    - echo "hello from dummy main ${PY}"

